#!/bin/bash

if [[ $OS == Windows_NT ]]; then
    echo Windows
    sdccrm=.make/sdccrm.exe
    sdasstm8='/c/Program Files/SDCC/bin/sdasstm8.exe'
else
    echo Linux
    sdccrm=sdccrm
    sdasstm8=sdasstm8
fi
"$sdccrm" $(tr '\r\n' ' ' < exclude_reference.txt) -r $@


for soubor in $@; do 
    "$sdasstm8" -plosg -ff $soubor; 
done
