#!/bin/bash

if [[ $OS == Windows_NT ]]; then
    echo Windows
    sdccrm=.make/sdccrm.exe
    sdasstm8='/c/Program Files/SDCC/bin/sdasstm8.exe'
else
    echo Linux
    sdccrm=sdccrm
    sdasstm8=sdasstm8
fi

output=$(node .make/exclude_reference $@ --sdccrm=$sdccrm)

"$sdccrm" $output -r $@

if [ $? -ne 0 ]; then
  echo "$output"
  exit 1
fi

for soubor in $@; do 
    "$sdasstm8" -plosg -ff $soubor; 
done
